#!/usr/bin/perl
#
# Script for generating pronounceable gibberish, an ok basis for passwords.
# Wrote this ages ago. 
# Stole the syllables from shorl.com.  (koremutake! - http://shorl.com/koremutake )
# - larcher@spoon.cx

use strict;
my @syllables = ('BA','BE','BI','BO','BU','BY','DA','DE','DI','DO','DU','DY','FA','FE','FI','FO','FU','FY','GA','GE','GI','GO','GU','GY','HA',
'HE','HI','HO','HU','HY','JA','JE','JI','JO','JU','JY','KA','KE','KI','KO','KU','KY','LA','LE','LI','LO','LU','LY','MA','ME','MI','MO','MU','MY
','NA','NE','NI','NO','NU','NY','PA','PE','PI','PO','PU','PY','RA','RE','RI','RO','RU','RY','SA','SE','SI','SO','SU','SY','TA','TE','TI','TO','
TU','TY','VA','VE','VI','VO','VU','VY','BRA','BRE','BRI','BRO','BRU','BRY','DRA','DRE','DRI','DRO','DRU','DRY','FRA','FRE','FRI','FRO','FRU','F
RY','GRA','GRE','GRI','GRO','GRU','GRY','PRA','PRE','PRI','PRO','PRU','PRY','STA','STE','STI','STO','STU','STY','TRA','TRE');
my $word ="";
my $numSyl = 6;
for (my $i = 0; $i < $numSyl; $i++) {
  $word .= $syllables[rand($#syllables)];
}
$word = lc($word);

print "$word (". length ($word ). ")\n";

